services:
  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - /opt/appdata/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - caddy
      - homeassistant
networks:
  caddy:
    external: true
  homeassistant:
    external: true

#fix