services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_REMOTE_AGENT=${LEYLA_IP}:${DOZZLE_AGENT_PORT}
    ports:
      - ${DOZZLEPORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock