services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    volumes:
      - /opt/appdata/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - caddy
      - homeassistant

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /opt/appdata/config/mqtt:/mosquitto/config:rw
      - /opt/appdata/data/mqtt:/mosquitto/data:rw
    networks:
      - homeassistant

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /opt/appdata/data/z2m/:/app/data
      - /run/udev:/run/udev:ro
    networks:
      - homeassistant
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_1c2f4549bf45ed119fa5c68f0a86e0b4-if00-port0:/dev/ttyUSB0

networks:
  caddy:
    external: true
  homeassistant:
    external: true

