services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ../files/configuration.yaml:/config/configuration.yaml
      - homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == docker

volumes:
  homeassistant-config: