services:
  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - arr
    ports:
      - ${RADARRPORT}:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGDIR}/radarr:/config
      - ${MEDIADIR}:/data
  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - arr
    ports:
      - ${SONARRPORT}:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGDIR}/sonarr:/config
      - ${MEDIADIR}:/data

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - arr
    ports:
      - "${PROFILARRPORT}:6868"
    volumes:
      - ${CONFIGDIR}/profilarr:/config

# NETWORKS
networks:
  arr:
    name: arr
