  sabnzbd:
    image: ghcr.io/hotio/sabnzbd:latest
    logging:
      driver: json-file
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/config/sabnzbd:/config
      - /vault/data/usenet:/data/usenet:rw
    networks:
      - arr
    deploy:
      placement:
        constraints:
          - node.hostname == aiko

networks:
  arr:
    external: true