services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stoppeds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8083:8080
    environment:
      - DOZZLE_REMOTE_AGENT=192.168.50.3:7007
