networks:
  arr:
    external: true

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    networks: [arr]
    volumes:
      - /opt/appdata/config/recyclarr:/config
    environment:
      - TZ=Europe/Brussels