services:
  headscale:
    image: docker.io/headscale/headscale:latest
    restart: unless-stopped
    container_name: headscale
    volumes:
      - /opt/appdata/config/headscale:/etc/headscale
      - /opt/appdata/data/headscale/lib:/var/lib/headscale
      - /opt/appdata/data/headscale/lib/run:/var/run/headscale
    command: serve
    networks:
      - caddy

networks:
  caddy:
    external: true