services:
  headplane:
    image: ghcr.io/tale/headplane:latest
    container_name: headplane
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - '/opt/appdata/config/headplane/config.yaml:/etc/headplane/config.yaml'
      - '/opt/appdata/config/headscale/config.yaml:/etc/headscale/config.yaml'
      - '/opt/appdata/data/headplane:/var/lib/headplane'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  headscale:
    image: headscale/headscale:latest
    networks:
      - caddy
    container_name: headscale
    restart: unless-stopped
    command: serve
    labels:
      me.tale.headplane.target: headscale
    volumes:
      - '/opt/appdata/data/headscale:/var/lib/headscale'
      - '/opt/appdata/config/headscale:/etc/headscale'

networks:
  caddy:
    external: true