services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    command: agent
    ports:
      - 7007:7007
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  caddy:
    external: true
