services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /opt/appdata/config/jellyfin:/config
      - /vault/data/media/tv:/data/tvshows
      - /vault/data/media/movies:/data/movies
    networks:
      - caddy


networks:
  caddy:
    external: true
