---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /opt/appdata/config/jellyfin/tv:/config
      - /opt/appdata/data/media/tv:/data/tvshows
      - /opt/appdata/data/media/movies:/data/movies
    restart: unless-stopped
    networks:
      - caddy
    deploy:
      placement:
        constraints:
          - node.hostname == aiko
      labels:
        caddy: http://jellyfin.15092006.xyz
        caddy.reverse_proxy: "{{upstreams 8096}}"

networks:
  caddy:
    external: true
    