services:
  jellyfin:
    image: jellyfin/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /opt/appdata/config/jellyfin:/config
      - /vault/data/media/tv:/data/tvshows
      - /vault/data/media/movies:/data/movies
    ports:
      - 8096:8096
    networks:
      - caddy
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]




networks:
  caddy:
    external: true
