---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - TZ=Europe/Brussels
    ports:
      - 7878:7878
    volumes:
      - /opt/appdata/config/radarr:/config
      - /vault/data:/data
    networks:
      - arr
    deploy:
      placement:
        constraints:
          - node.hostname == aiko

networks:
  arr:
    external: true