---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Europe/Brussels    
    networks:
      - caddy
      - arr
    ports:
      - 5055:5055
    volumes:
      - /opt/appdata/config/jellyseerr:/app/config
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  caddy:
    external: true
  arr:
    external: true